[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["src"]

[tool.ruff]
line-length = 100
target-version = "py311"
src = ["src"]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E501"] # длину строки уже контролирует black
fix = true

[tool.mypy]
python_version = "3.11"
strict = false
ignore_missing_imports = true
pretty = true
warn_unused_ignores = true
show_error_codes = true
plugins = []

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
